# Generated by Django 4.1.4 on 2022-12-12 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autores',
            fields=[
                ('id_autor', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=60, verbose_name='Nombres')),
                ('especialidad', models.CharField(max_length=50, verbose_name='Especialidad')),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autores',
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=50, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=50, verbose_name='Apellidos')),
                ('fec_nac', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('correo', models.EmailField(max_length=100, verbose_name='Correo')),
                ('password', models.CharField(max_length=150, verbose_name='Contraseña')),
                ('estado', models.CharField(choices=[('A', 'Saludable'), ('B', 'Enfermo'), ('C', 'Recuperado')], default='A', max_length=1, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
        migrations.CreateModel(
            name='Registros',
            fields=[
                ('id_registro', models.AutoField(primary_key=True, serialize=False)),
                ('fec_reg', models.DateTimeField(verbose_name='Registro')),
                ('temperatura', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Temperatura')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.usuarios')),
            ],
            options={
                'verbose_name': 'Registro',
                'verbose_name_plural': 'Registros',
            },
        ),
        migrations.CreateModel(
            name='Recomendaciones',
            fields=[
                ('id_recomendacion', models.AutoField(primary_key=True, serialize=False)),
                ('detalles', models.TextField()),
                ('fec_pub', models.DateField(verbose_name='Fecha de Publicacion')),
                ('tipo', models.CharField(choices=[('A', 'Saludable'), ('B', 'Enfermo'), ('C', 'Recuperado')], default='A', max_length=1, verbose_name='Tipo')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.autores')),
            ],
            options={
                'verbose_name': 'Recomendacion',
                'verbose_name_plural': 'Recomendaciones',
            },
        ),
        migrations.CreateModel(
            name='Contactos',
            fields=[
                ('id_contacto', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=50, verbose_name='Nombres')),
                ('correo', models.EmailField(max_length=100, verbose_name='Correo')),
                ('celular', models.IntegerField()),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Api.usuarios')),
            ],
            options={
                'verbose_name': 'Contacto',
                'verbose_name_plural': 'Contactos',
            },
        ),
    ]
