# Generated by Django 4.1.4 on 2022-12-12 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recomendaciones',
            name='titulo',
            field=models.CharField(default=1, max_length=50, verbose_name='Titulo'),
            preserve_default=False,
        ),
    ]
