# Generated by Django 4.1.4 on 2022-12-12 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0002_recomendaciones_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recomendaciones',
            name='tipo',
            field=models.CharField(choices=[('Saludable', 'Saludable'), ('Enfermo', 'Enfermo'), ('Recuperado', 'Recuperado')], max_length=10, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='estado',
            field=models.CharField(choices=[('Saludable', 'Saludable'), ('Enfermo', 'Enfermo'), ('Recuperado', 'Recuperado')], max_length=10, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='password',
            field=models.CharField(max_length=150, verbose_name='ContraseÃ±a'),
        ),
    ]
