# Generated by Django 4.1.4 on 2022-12-12 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0004_remove_recomendaciones_autor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recomendaciones',
            old_name='id_recomendacion',
            new_name='id',
        ),
    ]
